backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: duckck
    api_key: 184259328425148

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Vídeo, name: video, widget: file}
              - {label: Título, name: title, widget: markdown}
              - {label: Subtítulo 1, name: subtitle, widget: string}
              - {label: Subtítulo 2, name: subtitle2, widget: string}
              - {label: Texto do CTA, name: cta_text, widget: string}
              - {label: Link do CTA, name: cta_link, widget: string}
          - label: Empreendimento em Destaque
            name: empreendimento
            widget: relation
            collection: empreendimentos
            valueField: "title"
            searchFields: ["title"]
          - label: Sustentabilidade
            name: sustentabilidade
            widget: object
            fields:
              - {label: Título, name: title, widget: markdown}
              - {label: Texto, name: text, widget: markdown}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Título Curto, name: title, widget: string}
                  - {label: Título Completo, name: complete_title, widget: string}
                  - {label: Texto, name: text, widget: text}
                  - {label: "Estilo 'para baixo'", name: "bottom", widget: "boolean", default: false}
                  - label: Imagem de Fundo
                    name: image
                    widget: image
                    media_library:
                      config:
                        default_transformations:
                          - - fetch_format: auto
                              width: 300
                              height: 300
                              quality: auto
                              crop: crop
                  - label: Ícone Externo
                    name: external_icon
                    widget: image
                    media_library:
                      config:
                        default_transformations:
                          - - fetch_format: auto
                              width: 65
                              height: 65
                              quality: auto
                              crop: pad
                  - label: Ícone Interno
                    name: internal_icon
                    widget: image
                    media_library:
                      config:
                        default_transformations:
                          - - fetch_format: auto
                              width: 40
                              height: 40
                              quality: auto
                              crop: pad
          - label: Midia
            name: midia
            widget: object
            fields:
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Título, name: title, widget: string}
                  - {label: Link, name: link, widget: string}
                  - label: Imagem
                    name: image
                    widget: image
                    media_library:
                      config:
                        default_transformations:
                          - - fetch_format: auto
                              width: 300
                              height: 300
                              quality: auto
                              crop: crop

  - name: empreendimentos
    label: Empreendimentos
    folder: "data/empreendimentos"
    create: true
    extension: "yml"
    fields:
      - {label: Título, name: title, widget: string}
      - {label: Subtítulo, name: subtitle, widget: string}
      - {label: Valor, name: value, widget: string}
      - {label: Cidade, name: city, widget: string}
      - label: Imagem
        name: image
        widget: image
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto
                  width: 1900
                  height: 750
                  quality: auto
                  crop: crop
      - label: Imagens quando destaque
        name: highlight_images
        widget: list
        fields:
          - label: Imagem
            name: image
            widget: image
            media_library:
              config:
                default_transformations:
                  - - fetch_format: auto
                      width: 945
                      height: 600
                      quality: auto
                      crop: crop
      - {label: Texto quando destaque, name: highlight_text, widget: markdown}
      - {label: Andamento, name: status, widget: string}
      - {label: "Aparecer 8 razões para comprar uma casa?", name: show_reasons, widget: boolean, default: false}
      - {label: "Texto de Introdução", name: text, widget: text}
      - label: Condomínio
        name: condominio
        widget: relation
        collection: condominios
        valueField: "title"
        searchFields: ["title"]
      - label: Detalhes
        name: details
        widget: list
        fields:
          - {label: Detalhe, name: title, widget: string}
      - {label: "Vídeo de fundo", name: background_video, widget: file }
      - {label: "Código do Vídeo do Youtube", name: youtube_video, widget: string }
      - label: Seções de Fotos
        name: image_sections
        widget: list
        fields:
          - {label: Título, name: title, widget: string}
          - label: Imagens
            name: images
            widget: list
            fields:
              - label: Imagem
                name: image
                widget: image
                media_library:
                  config:
                    default_transformations:
                      - - fetch_format: auto
                          width: 1900
                          quality: auto
                          crop: limit
      - label: Plantas
        name: plants
        widget: list
        fields:
          - {label: Título, name: title, widget: string}
          - label: Imagem
            name: image
            widget: image
            media_library:
              config:
                default_transformations:
                  - - fetch_format: auto
                      width: 1050
                      quality: auto
                      crop: limit
      - label: Detalhes Adicionais
        name: more_details
        widget: list
        fields:
          - {label: Detalhe, name: title, widget: string}

  - name: condominios
    label: Condomínios
    folder: "data/condominios"
    create: true
    extension: "yml"
    fields:
      - {label: Nome, name: title, widget: string}
      - {label: Cidade, name: city, widget: string}
      - {label: Texto, name: text, widget: markdown}
      - label: Image
        name: image
        widget: image
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto
                  width: 1900
                  height: 600
                  quality: auto
                  crop: crop
      - {label: Valor, name: value, widget: string}
      - label: Seções
        name: sections
        widget: list
        fields:
          - {label: Nome, name: title, widget: string}
          - label: Image
            name: image
            widget: image
            media_library:
              config:
                default_transformations:
                  - - fetch_format: auto
                      width: 600
                      height: 900
                      quality: auto
                      crop: crop
          - label: Detalhes
            name: details
            widget: list
            fields:
              - {label: Texto, name: text, widget: text}

  - file: data/reasons.yml
    label: 8 Razões para comprar uma casa
    name: reasons
    fields:
      - {label: Título, name: title, widget: markdown}
      - label: Itens
        name: items
        widget: list
        fields:
          - {label: Título, name: title, widget: string}
          - {label: Texto, name: text, widget: text}
          - label: Ícone
            name: icon
            widget: image
            media_library:
              config:
                default_transformations:
                  - - fetch_format: auto
                      width: 60
                      height: 60
                      quality: auto
                      crop: pad

  - name: settings
    label: Configurações
    files:
      - file: data/settings/infos.yml
        label: Informações
        name: infos
        fields:
          - {label: Direitos Reservados, name: rights, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Whatsapp, name: whatsapp, widget: string}
          - {label: Telefone, name: phone, widget: string}
          - {label: Endereço, name: address, widget: markdown}

      # - file: data/settings/navigation.yml
      #   label: Navigation
      #   name: navigation
      #   fields:
      #     - label: Navigation
      #       name: nav_items
      #       widget: list
      #       fields:
      #         - {label: Label, name: label, widget: string}
      #         - {label: Path, name: path, widget: string}
