backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: duckck
    api_key: 184259328425148

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Vídeo, name: video, widget: file}
              - {label: Título, name: title, widget: string}
              - {label: Subtítulo 1, name: subtitle, widget: string}
              - {label: Subtítulo 2, name: subtitle2, widget: string}
              - {label: Texto do CTA, name: cta_text, widget: string}
              - {label: Link do CTA, name: cta_link, widget: string}

  # - name: settings
  #   label: Configurações
  #   files:
  #     - file: data/settings/navigation.yml
  #       label: Navigation
  #       name: navigation
  #       fields:
  #         - label: Navigation
  #           name: nav_items
  #           widget: list
  #           fields:
  #             - {label: Label, name: label, widget: string}
  #             - {label: Path, name: path, widget: string}
